cfg_name: smad_forelimb_vp_autoencoder
model_name: LstmAutoencoderPk
module: smad.models.autoencoders
params:
  model:
    hidden_size: 32
    input_size: 2
    latent_dim: 8
    num_encoder_layers: 2
    num_decoder_layers: 2
    pooling: True
    dropout: 0.05
    skip_connections: True
  training:
    batch_size: 32
    criterion: MSELoss
    epochs: 200
    learning_rate: 0.0001
    optimizer: Adam
    autoregressive_ft:
      epochs: 5
      learning_rate: 0.00001
