name: Autoencoder

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Disk space (prior)
        run: df -h
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean
          df -h
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: smad
          python-version: 3.11
          auto-activate-base: false
      - name: Disk space (post)
        shell: bash -l {0}
        run: |
          df -h
          conda info
          conda env list
          conda clean -a -y || true
      - name: Autoencoder Training Test
        shell: bash -l {0}
        run: |
          pytest --maxfail=1 --disable-warnings -q
  
  merge:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/development' && success() # only run if tests pass
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge dev > main 
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git fetch origin main
          git fetch origin development
          git checkout main
          git merge --ff-only origin/development
          git push origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}